### ISSUE TITLE
Not enough arguments in call to client.cmdable.Ping

### ISSUE THREAD

**Issue by zefonseca** [ava-labs/ortelius#16]
Running `docker-compose` Yields error:

```
sudo docker-compose -f docker/docker-compose.yml up

Building stream-consumer
Step 1/12 : FROM golang:1.14-alpine
 ---> 3289bf11c284
Step 2/12 : WORKDIR /go/src/github.com/ava-labs/ortelius
 ---> Using cache
 ---> 4bd53078b885
Step 3/12 : RUN apk add git
 ---> Using cache
 ---> 6560f4274925
Step 4/12 : COPY . .
 ---> Using cache
 ---> ae70d19018f4
Step 5/12 : RUN go get ./cmds/...
 ---> Running in 8c72d7b6d846
# github.com/ava-labs/ortelius/services
services/connections.go:69:23: not enough arguments in call to client.cmdable.Ping
	have ()
	want (context.Context)
ERROR: Service 'stream-consumer' failed to build: The command '/bin/sh -c go get ./cmds/...' returned a non-zero code: 2

```

Running ava 0.5.1

**Comment by zefonseca** [comment]
Seems like redis recently made backward incompatible API changes: https://github.com/go-redis/redis/issues/1333

May be solved by #17

**Comment by zefonseca** [comment]
The build still fails after #17. Same error on `services/avm_index/redis.go`

```
# github.com/ava-labs/ortelius/services/avm_index
services/avm_index/redis.go:44:20: not enough arguments in call to pipe.Set
	have (string, []byte, number)
	want (context.Context, string, interface {}, time.Duration)
services/avm_index/redis.go:48:21: not enough arguments in call to pipe.Incr
	have (string)
	want (context.Context, string)
services/avm_index/redis.go:52:22: cannot use recentTxsKey (type string) as type context.Context in argument to pipe.LPush:
	string does not implement context.Context (missing Deadline method)
services/avm_index/redis.go:56:22: not enough arguments in call to pipe.LTrim
	have (string, number, number)
	want (context.Context, string, int64, int64)
services/avm_index/redis.go:60:21: not enough arguments in call to pipe.Exec
	have ()
	want (context.Context)
services/avm_index/redis.go:66:21: not enough arguments in call to r.client.cmdable.Get
	have (string)
	want (context.Context, string)
services/avm_index/redis.go:75:21: not enough arguments in call to r.client.cmdable.Get
	have (string)
	want (context.Context, string)
services/avm_index/redis.go:84:24: not enough arguments in call to r.client.cmdable.LRange
	have (string, number, int64)
	want (context.Context, string, int64, int64)
ERROR: Service 'stream-consumer' failed to build: The command '/bin/sh -c go get ./cmds/...' returned a non-zero code: 2

```

Passing client.Context() as first parameter leads to a successful build:

```
Step 5/12 : RUN go get ./cmds/...
 ---> Using cache
 ---> 25bcc524fba4
Step 6/12 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /opt/orteliusd ./cmds/orteliusd/*.go
 ---> Using cache
 ---> ff2bdb53f029
Step 7/12 : FROM scratch
 ---> 
Step 8/12 : VOLUME /var/log/ortelius
 ---> Using cache
 ---> 5c98b86b0f65
Step 9/12 : VOLUME /var/lib/ortelius
 ---> Using cache
 ---> 76e5b4eac49e
Step 10/12 : COPY --from=0 /opt/orteliusd /opt/orteliusd
 ---> Using cache
 ---> 130f04e45ee2
Step 11/12 : COPY --from=0 /go/src/github.com/ava-labs/ortelius/docker/config.json /var/lib/ortelius/config.json
 ---> Using cache
 ---> c1b85b4dfab1
Step 12/12 : ENTRYPOINT ["/opt/orteliusd"]
 ---> Using cache
 ---> 55dd94a01b3b
Successfully built 55dd94a01b3b
Successfully tagged docker_api:latest
```

Updated #17

**Comment by tyler-smith** [comment]
This is fixed now. Thanks for the report.
